# Generated by Django 3.2.6 on 2021-08-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='sub_department',
            name='dept',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='records',
        ),
        migrations.DeleteModel(
            name='sub_department',
        ),
    ]
