# Generated by Django 3.2.6 on 2021-08-29 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0002_auto_20210829_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('organize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='sub_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_dept_name', models.CharField(max_length=50)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.department')),
                ('organize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sub_dept_name'],
            },
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sr_no', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('position', models.CharField(blank=True, max_length=25)),
                ('l_vax', models.DateField()),
                ('no_vax', models.IntegerField()),
                ('status', models.CharField(default='negative', max_length=8)),
                ('covi_date', models.DateField(blank=True)),
                ('certificate', models.FileField(upload_to='certificates')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.sub_department')),
                ('organize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
