# Generated by Django 3.2.6 on 2021-08-29 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covid', '0003_department_records_sub_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='records',
            new_name='recordss',
        ),
        migrations.AlterField(
            model_name='recordss',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid.department'),
        ),
        migrations.DeleteModel(
            name='sub_department',
        ),
    ]
