# Generated by Django 3.2.6 on 2021-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0006_auto_20210830_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordss',
            name='covid_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordss',
            name='vaccine_certificate',
            field=models.FileField(blank=True, upload_to='certificates/'),
        ),
    ]
