# Generated by Django 3.2.6 on 2021-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0007_auto_20210830_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordss',
            name='status',
            field=models.CharField(max_length=8),
        ),
    ]
